include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    included_file_warning: ignore
    lines_longer_than_80_chars: ignore
    invalid_annotation_target: ignore
    no_default_cases: ignore
    strict_raw_type: ignore
    use_setters_to_change_properties: ignore
    one_member_abstracts: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.graphql.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"

linter:
  rules:
    always_put_required_named_parameters_first: false
    public_member_api_docs: false
    avoid_print: false
    library_private_types_in_public_api: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    