name: kliq_movies
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #UI  
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  another_flushbar: ^1.12.30
  get_time_ago: ^1.3.1

  #network request
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  logger: any 

  #route
  auto_route: ^8.1.3

  #state management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod: ^2.5.1


  #functional programming
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0

  #local storage
  path_provider: ^2.1.1
  hive: ^2.2.3
  
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  freezed: ^2.4.5
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  fonts:        
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

